version: 2

jobs:
  frontend_setup:
    docker:
      - image: circleci/node:8.12.0

    working_directory: ~/node

    steps:
      - checkout

      - restore_cache:
          keys:
          - node_modules-{{ checksum "frontend/package.json" }}

      - run:
         command: npm install
         working_directory: frontend

      - save_cache:
          paths:
            - frontend/node_modules
          key: node_modules-{{ checksum "frontend/package.json" }}

      - persist_to_workspace:
          root: ~/
          paths: ./*

  frontend_build_development:
    docker:
      - image: circleci/node:8.12.0

    working_directory: ~/node

    steps:
      - attach_workspace:
          at: ~/

      - run:
         command: npm run build
         working_directory: frontend

  frontend_build_production:
      docker:
        - image: circleci/node:8.12.0

      working_directory: ~/node

      steps:
        - attach_workspace:
            at: ~/

        - run:
           command: npm run build -- --prod
           working_directory: frontend

        - persist_to_workspace:
            root: ~/
            paths: ./*

  frontend_deploy:
    docker:
      - image: circleci/node:8.12.0

    working_directory: ~/node

    steps:
      - attach_workspace:
          at: ~/

      - run: git config --global user.name "Marei Kikukawa"
      - run: git config --global user.email "contact@marei.jp"

      - run:
         command: npm run deploy
         working_directory: frontend

  backend_deploy:
    docker:
      - image: circleci/python:3.7.0

    working_directory: ~/python

    steps:
      - checkout

      - run: git config --global user.name "Marei Kikukawa"
      - run: git config --global user.email "contact@marei.jp"
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git `git subtree split --prefix backend master`:master --force

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - frontend_setup:
          filters:
              branches:
                ignore: gh-pages

      - frontend_build_development:
          requires:
            - frontend_setup

      - frontend_build_production:
          requires:
            - frontend_setup

      - frontend_deploy:
          requires:
            - frontend_build_development
            - frontend_build_production

          filters:
            branches:
              only: master

      - backend_deploy:
          filters:
            branches:
              only: master
